version: "3.3"

services:

  selenium-hub:
    image: selenium/hub:4.9.1-20230508
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 10
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIME_OUT: 300

  chrome:
    image: selenium/node-chrome
    container_name: chrome-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_MAX_INSTANCES=5

  firefox:
    image: selenium/node-firefox
    container_name: firefox-node
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "5902:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_MAX_INSTANCES=5

#  edge:
#    image: selenium/node-edge
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    ports:
#      - "5903:5900"
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#      - SE_NODE_MAX_SESSIONS=5
#      - SE_NODE_MAX_INSTANCES=5

#  safari:
#    image: browsers/safari:15.0
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    ports:
#      - "5903:5900"
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
#      - SE_NODE_MAX_SESSIONS=5
#      - SE_NODE_MAX_INSTANCES=5
